# Generated by Django 2.0.1 on 2018-01-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSignupModel',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('city', models.TextField()),
                ('state', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('current_weather', models.TextField(null=True)),
                ('current_tempurature', models.FloatField(null=True)),
                ('past_tempurature', models.FloatField(null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='weathermodel',
            unique_together={('city', 'state')},
        ),
    ]
